import type { Metadata } from "next";

import "./globals.css";
import Header from "@/app/components/Header/Header"
import Footer from "@/app/components/Footer/Footer";
import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        {/* header */}
        <nav>
          <Header />
        </nav>
        {children}
        {/* footer */}
        <footer className="  p-4 text-center">
          <Footer />
        </footer>

      </body>
    </html>
  );
}
